---
title: "plots"
author: "Iara Diamela Rodriguez"
editor_options: 
  chunk_output_type: console
---

```{r setup, eval=T,echo=FALSE }

knitr::opts_chunk$set(echo = TRUE)

load(".RData")

require(igraph)
require(NetIndices)
require(multiweb)

require(ggplot2)

require(dplyr)
require(knitr)
require(devtools)
require(cowplot)


# Typography

require(extrafont)
font_import()
loadfonts()
loadfonts(device="win")

# Color palette

colnet <- c("#024828","#066e3f","#088a4f","#51b487","#85caab","#a8d9c3", #green +dark-
            "#ffffff", #white
            "#40004b","#683272","#833f8f","#9970ab","#b79ac4","#ccb7d5") #purple +dark-

# Plots' theme

theme_new <- theme_minimal() +
             theme(axis.title.x=element_text(size=18, face="bold", family="Lato", margin=margin(t=8, r=0, b=0, l=0)),
                   axis.text.x=element_text(size=10, color="black", family="Lato"), 
                   axis.title.y = element_text(face="bold", size=15, vjust=rel(3), family="Lato"),
                   axis.text.y=element_text(size=10, color="black", family="Lato"),
                   plot.title=element_text(family="Lato", face="bold", size=20, hjust=0.5),
                   panel.grid.major=element_line(color="gray50", linetype="dotted", size=rel(0.6)),
                   panel.grid.minor=element_line(color="gray85", linetype="dotted", size=rel(0.5)),
                   panel.background=element_rect(fill="gray98", color="white"),
                   legend.text=element_text(size=16, family="Lato"),
                   legend.title=element_text(face="bold", size=16, family="Lato"),
                   legend.position="bottom")

```


### Food web plot by trophic level and modules ###

```{r plotFW, echo=FALSE, message=FALSE}

troph.net1 <- TrophInd(get.adjacency(p, sparse=F), Dead=c("Necromass", "Fresh detritus", "Aged detritus"))
layout.matrix.1 <- matrix(nrow=length(V(p)), ncol=2)

troph.net2 <- TrophInd(get.adjacency(b, sparse=F), Dead=c("Necromass", "Fresh detritus", "Aged detritus"))
layout.matrix.2 <- matrix(nrow=length(V(b)), ncol=2)
  
# Add colors with topological roles to nodes 
colnet1 <- c("#833f8f", "#ccb7d5","#a8d9c3", "#088a4f")
  
hcp <- hub_connp %>% mutate(type = factor(type)) %>% arrange(node) %>% mutate(col=as.numeric(type), TL=troph.net1[,1]) 
V(p)$color <- colnet1[hcp$col]

hcb <- hub_connb %>% mutate(type = factor(type)) %>% arrange(node) %>% mutate(col=as.numeric(type), TL=troph.net2[,1]) 
V(b)$color <- colnet1[hcb$col]
  
# Transform y-axis coordinates
maxnewp <- max(hcp$TL)
minnewp <- min(hcp$TL)

maxnewb <- max(hcb$TL)
minnewb <- min(hcb$TL)

maxold <- 1
minold <- -1

t1 <- function(x) (maxold-minold)/(maxnewp-minnewp)*(x-maxnewp)+maxold 
t2 <- function(x) (maxold-minold)/(maxnewb-minnewb)*(x-maxnewb)+maxold

# Plot modules
layout.matrix.1[,2] <- jitter(troph.net1$TL, 1.05) # y-axis value based on trophic level
layout.matrix.1[,1] <- jitter(mod_by_red[[1]]$membership, 1.2) # randomly assign along x-axis

layout.matrix.2[,2] <- jitter(troph.net2$TL, 0.4)
layout.matrix.2[,1] <- jitter(mod_by_red[[2]]$membership, 1.4)

svg("Results/fw_mod_TL.svg", width=20, height=10)
par(mfrow=c(1,2), mar=c(0,0.5,0,0), oma=c(0,1.5,2.3,0.5), family = "Lato")
require(prettyGraphs)

plot(p, 
     vertex.color=vertex_attr(p)$cor,
     vertex.frame.color="white",
     vertex.label=NA,
     vertex.size=1/7*degree(p)+4,
     edge.width=.4, 
     edge.arrow.size=F, 
     edge.color=add.alpha("grey80", 1),
     edge.curved=0.15,
     layout=layout.matrix.1)
axis(side=2, at=t1(1:5), labels=1:5, las=1, col=NA, col.ticks=1)

plot(b, 
     vertex.color=vertex_attr(b)$cor,
     vertex.frame.color="white",
     vertex.label=NA,
     vertex.size=1/7*degree(b)+4,
     edge.width=.4, 
     edge.arrow.size=F, 
     edge.color=add.alpha("grey80", 1),
     edge.curved=0.15,
     layout=layout.matrix.2)
axis(side=2, at=t1(1:5), labels=1:5, las=1, col=NA, col.ticks=1)

dev.off()

#svg("Results/fw_legend.svg", width=5, height=5)
#par(mfrow=c(1,1), mar=c(0,2,0,0), oma=c(0,1.5,2.3,0.5), family = "Lato")
# Add legend
#plot(0, 0, type="n", bty="n", xaxt="n", yaxt="n")
#legend("top", legend = c("Network connector", "Module connector", "Module specialist", "Module hub"), col=colnet, pch=19, cex=1, xpd=TRUE, inset=c(0,0), title="Topological roles:")
#dev.off()

```

### Plot traits (habitat & functional group) vs modules ###

```{r plotTrait, echo=FALSE, message=FALSE, results='asis'}

#--- Modules vs habitat 

#POTTER
#legendh <- get_legend(ph)
ph <- ggplot(cpH, aes(Mod, Freq, fill=factor(Habitat, levels=c("pelagic", "benthopelagic", "benthic")))) + 
      geom_bar(stat="identity", position="stack", show.legend=FALSE) + 
      scale_fill_manual(values=c(colnet[5], "#fee091", colnet[12]), 
                    limits=c("pelagic", "benthopelagic", "benthic"), 
                    breaks=c("pelagic", "benthopelagic", "benthic"), 
                    name="Habitat", 
                    labels=c("Pelagic", "Benthopelagic", "Benthic")) + 
      labs(y="Species", x="Modules") + 
      ggtitle("Potter Cove") +
      coord_cartesian(ylim=c(0, 70)) +
      theme_new +
      theme(legend.position="right")

#BEAGLE
bh <- ggplot(cbH, aes(Mod, Freq, fill=factor(Habitat, levels=c("pelagic", "benthopelagic", "benthic")))) + 
      geom_bar(stat="identity", position="stack", show.legend=FALSE) + 
      scale_fill_manual(values=c(colnet[5], "#fee091", colnet[12]), 
                    limits=c("pelagic", "benthopelagic", "benthic"), 
                    breaks=c("pelagic", "benthopelagic", "benthic"), 
                    name="", 
                    labels=c("Pelagic", "Benthopelagic", "Benthic")) + 
      labs(y="", x="") +
      ggtitle("Beagle Channel") +
      coord_cartesian(ylim=c(0, 70)) + 
      theme_new

#--- Modules vs functional group

#POTTER
#legendfg <- get_legend(pfg)
pfg<- ggplot(cpFG, aes(Mod, Freq, fill=factor(FG, levels=c("basal taxa", "zooplankton", "non-living", "benthos", "fish")))) + 
      geom_bar(stat="identity", position="stack", show.legend=FALSE) + 
      scale_fill_manual(values=c("#39a172", colnet[5], "#fee091","#c5aecf", "#896499"), 
                    limits=c("basal taxa", "zooplankton", "non-living", "benthos", "fish"), 
                    breaks=c("basal taxa", "zooplankton", "non-living", "benthos", "fish"), 
                    name="Functional group", 
                    labels=c("Basal taxa", "Zooplankton", "Detritus", "Benthos", "Fish")) + 
      labs(y="Species", x="Modules") + 
      coord_cartesian(ylim=c(0, 70)) +
      theme_new +
      theme(legend.position="right")

#BEAGLE
bfg <- ggplot(cbFG, aes(Mod, Freq, fill=factor(FG, levels=c("basal taxa", "zooplankton", "non-living", "benthos", "fish")))) + 
       geom_bar(stat="identity", position="stack", show.legend=FALSE) +
       scale_fill_manual(values=c("#39a172", colnet[5], "#fee091","#c5aecf", "#896499"),  
                    limits=c("basal taxa", "zooplankton", "non-living", "benthos", "fish"), 
                    breaks=c("basal taxa", "zooplankton", "non-living", "benthos", "fish"), 
                    name="Functional group", 
                    labels=c("Basal taxa", "Zooplankton", "Detritus", "Benthos", "Fish")) + 
       labs(y="", x="Modules") +
       coord_cartesian(ylim=c(0, 70)) +
       theme_new

# Add all plots into a single plot

hfg <-  list(ph, pfg, legendh, legendfg, bh, bfg)
col1 <- plot_grid(hfg[[1]], hfg[[2]], ncol=1, nrow=2, labels = c("(a)", "(c)"), label_size=15, label_fontfamily="Lato", hjust=0.25, vjust=2)
col2 <- plot_grid(hfg[[3]], hfg[[4]], ncol=1, nrow=2)
col3 <- plot_grid(hfg[[5]], hfg[[6]], ncol=1, nrow=2, labels = c("(b)", "(d)"), label_size=15, label_fontfamily="Lato", hjust=0.25, vjust=2)
plot_grid(col1, col2, col3, ncol=3, rel_widths=c(1,0.35,1), scale=0.98)

ggsave("Results/HFG_PCBC.svg", width=13, height=12)

rm(ph,bh,pfg,bfg,hfg,col1,col2,col3)

```

```{r, echo=FALSE, message=FALSE, results='asis'}

# Total spp x traits plots

#-- Habitat

#POTTER
cpH_t <- cpH %>% group_by(Habitat) %>% summarise(Total=(sum(Freq)/110)*100)
ggplot(cpH_t, aes(x=1, y=Total, fill=Habitat)) +
       geom_bar(stat="identity", show.legend=FALSE) +
       scale_fill_manual(values=c(colnet[5], "#fee091", colnet[12]), 
                         limits=c("pelagic", "benthopelagic", "benthic"), 
                         breaks=c("pelagic", "benthopelagic", "benthic")) +
       geom_text(aes(label=paste0(round(Total,0), "%")),
                 hjust=1.5, vjust=-11,
                 size=4.25, family="Lato", fontface="bold") +
       coord_polar(theta="y") + 
       labs(y="", x="") +
       theme_void()
ggsave("Results/cpH_t.svg", width=5, height=5)

#BEAGLE
cbH_t <- cbH %>% group_by(Habitat) %>% summarise(Total=(sum(Freq)/145)*100)
ggplot(cbH_t, aes(x=1, y=Total, fill=Habitat)) +
       geom_bar(stat="identity", show.legend=FALSE) +
       scale_fill_manual(values=c(colnet[5], "#fee091", colnet[12]), 
                    limits=c("pelagic", "benthopelagic", "benthic"), 
                    breaks=c("pelagic", "benthopelagic", "benthic")) +
       geom_text(aes(label=paste0(round(Total,0), "%")),
                 hjust=1.5, vjust=-12,
                 size=4.25, family="Lato", fontface="bold") +
       coord_polar(theta="y") + 
       labs(y="", x="") +
       theme_void()
ggsave("Results/cbH_t.svg", width=5, height=5)

#-- Functional group

#POTTER
cpFG_t <- cpFG %>% group_by(FG) %>% summarise(Total=(sum(Freq)/110)*100)
ggplot(cpFG_t, aes(x=1, y=Total, fill=FG)) +
        geom_bar(stat="identity", show.legend=FALSE) +
        scale_fill_manual(values=c("#39a172", colnet[5], "#fee091","#c5aecf", "#896499"), 
                    limits=c("basal taxa", "zooplankton", "non-living", "benthos", "fish"), 
                    breaks=c("basal taxa", "zooplankton", "non-living", "benthos", "fish")) +
       coord_polar(theta="y") + 
       labs(y="", x="") +
       theme_void()
ggsave("Results/cpFG_t.svg", width=5, height=5)

#BEAGLE
cbFG_t <- cbFG %>% group_by(FG) %>% summarise(Total=(sum(Freq)/145)*100)
ggplot(cbFG_t, aes(x=1, y=Total, fill=FG)) +
       geom_bar(stat="identity", show.legend=FALSE) +
       scale_fill_manual(values=c("#39a172", colnet[5], "#fee091","#c5aecf", "#896499"), 
                    limits=c("basal taxa", "zooplankton", "non-living", "benthos", "fish"), 
                    breaks=c("basal taxa", "zooplankton", "non-living", "benthos", "fish")) +
       coord_polar(theta="y") + 
       labs(y="", x="") +
       theme_void()
ggsave("Results/cbFG_t.svg", width=5, height=5)

rm(cpH_t,cbH_t,cpFG_t,cbFG_t)

```


### Plot structure and stability metrics ###

```{r plotTopology, echo=FALSE, message=FALSE, results='asis'}

datp <- ti %>% filter(Network=="Potter") #empiric metrics for Potter
simp <- tiMIC %>% filter(Network=="Potter") #curveball randomizations metrics for Potter

datb <- ti %>% filter(Network=="Beagle") #empiric metrics for Beagle
simb <- tiMIC %>% filter(Network=="Beagle") #curveball randomizations metrics for Beagle


# Mean trophic level

q1 <- quantile(simp$TLmean, c(0.005,0.995)) #95% confidence interval for Potter mean TL
q2 <- quantile(simb$TLmean, c(0.005,0.995)) #95% confidence interval for Beagle mean TL

#legend1 <- get_legend(g1)
g1 <- ggplot(tiMIC, aes(TLmean)) + 
      geom_histogram(data=tiMIC, aes(fill=Network), bins=50, show.legend=FALSE) +
      scale_fill_manual(values=c(colnet[12], colnet[5]), labels=c("Beagle Channel", "Potter Cove")) +
      xlab("Mean trophic level") + 
      ylab("Frequency") + 
      geom_segment(data=datp, aes(x=TLmean, xend=TLmean, y=45, yend=0), colour=colnet[2], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datp, aes(x=TLmean, y=-19, label=round(TLmean,1)), size=4.25, family="Lato", fontface="bold", colour=colnet[2]) +
      geom_segment(data=datp, aes(x=q1[1], xend=q1[1], y=35, yend=0), colour=colnet[2], size=1.25, linetype=1) +
      geom_segment(data=datp, aes(x=q1[2], xend=q1[2], y=35, yend=0), colour=colnet[2], size=1.25, linetype=1) + 
      geom_segment(data=datb, aes(x=TLmean, xend=TLmean, y=45, yend=0), colour=colnet[9], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datb, aes(x=TLmean, y=-23, label=round(TLmean,1)), size=4.25, family="Lato", fontface="bold", colour=colnet[9]) +
      geom_segment(data=datb, aes(x=q2[1], xend=q2[1], y=35, yend=0), colour=colnet[9], size=1.25, linetype=1) +
      geom_segment(data=datb, aes(x=q2[2], xend=q2[2], y=35, yend=0), colour=colnet[9], size=1.25, linetype=1) + 
      theme_new +
      coord_cartesian(ylim=c(-8, 600)) #+ guides(fill=guide_legend(reverse=TRUE))

# Omnivory

q3 <- quantile(simp$Omnivory, c(0.005,0.995))
q4 <- quantile(simb$Omnivory, c(0.005,0.995))

require(scales)
g2 <- ggplot(tiMIC, aes(Omnivory)) + 
      geom_histogram(data=simp, fill=colnet[5], color=colnet[5], bins=50) + 
      geom_histogram(data=simb, fill=colnet[12], color=colnet[12], bins=50) +
      xlab("Omnivory") + 
      ylab("") + 
      geom_segment(data=datp, aes(x=Omnivory, xend=Omnivory, y=52, yend=0), colour=colnet[2], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datp, aes(x=Omnivory, y=-26, label=percent(round(Omnivory,2))), size=4.25, family="Lato", fontface="bold", colour=colnet[2]) +
      geom_segment(data=datp, aes(x=q3[1], xend=q3[1], y=41, yend=0), colour=colnet[2], size=1.25, linetype=1) +
      geom_segment(data=datp, aes(x=q3[2], xend=q3[2], y=41, yend=0), colour=colnet[2], size=1.25, linetype=1) + 
      geom_segment(data=datb, aes(x=Omnivory, xend=Omnivory, y=52, yend=0), colour=colnet[9], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datb, aes(x=Omnivory, y=-26, label=percent(round(Omnivory,2))), size=4.25, family="Lato", fontface="bold", colour=colnet[9]) +
      geom_segment(data=datb, aes(x=q4[1], xend=q4[1], y=41, yend=0), colour=colnet[9], size=1.25, linetype=1) +
      geom_segment(data=datb, aes(x=q4[2], xend=q4[2], y=41, yend=0), colour=colnet[9], size=1.25, linetype=1) + 
      theme_new + 
      coord_cartesian(ylim=c(-10, 700)) + 
      scale_x_continuous(labels=percent_format(accuracy=1))

# Modularity

q5 <- quantile(simp$Modularity, c(0.005,0.995))
q6 <- quantile(simb$Modularity, c(0.005,0.995))

g3 <- ggplot(tiMIC, aes(Modularity)) + 
      geom_histogram(data=simp, fill=colnet[5], color=colnet[5], bins=50) + 
      geom_histogram(data=simb, fill=colnet[12], color=colnet[12], bins=50) +
      xlab("Modularity") + 
      ylab("Frequency") + 
      geom_segment(data=datp, aes(x=Modularity, xend=Modularity, y=9, yend=0), colour=colnet[2], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datp, aes(x=Modularity, y=-4.5, label=round(Modularity,2)), size=4.25, family="Lato", fontface="bold", colour=colnet[2]) +
      geom_segment(data=datp, aes(x=q5[1], xend=q5[1], y=7, yend=0), colour=colnet[2], size=1.25, linetype=1) +
      geom_segment(data=datp, aes(x=q5[2], xend=q5[2], y=7, yend=0), colour=colnet[2], size=1.25, linetype=1) + 
      geom_segment(data=datb, aes(x=Modularity, xend=Modularity, y=9, yend=0), colour=colnet[9], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datb, aes(x=Modularity, y=-4.5, label=round(Modularity,2)), size=4.25, family="Lato", fontface="bold", colour=colnet[9]) +
      geom_segment(data=datb, aes(x=q6[1], xend=q6[1], y=7, yend=0), colour=colnet[9], size=1.25, linetype=1) +
      geom_segment(data=datb, aes(x=q6[2], xend=q6[2], y=7, yend=0), colour=colnet[9], size=1.25, linetype=1) + 
      theme_new + 
      coord_cartesian(ylim=c(-2.75, 120))

#MEing

q7 <- quantile(simp$MEing, c(0.005,0.995))
q8 <- quantile(simb$MEing, c(0.005,0.995))

g4 <- ggplot(tiMIC, aes(MEing)) + 
      geom_histogram(data=simp, fill=colnet[5], color=colnet[5], bins=50) + 
      geom_histogram(data=simb, fill=colnet[12], color=colnet[12], bins=50) +
      xlab("QSS") + 
      ylab("") + 
      geom_segment(data=datp, aes(x=MEing, xend=MEing, y=30, yend=0), colour=colnet[2], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datp, aes(x=MEing, y=-15, label=round(MEing,1)), size=4.25, family="Lato", fontface="bold", colour=colnet[2]) +
      geom_segment(data=datp, aes(x=q7[1], xend=q7[1], y=23, yend=0), colour=colnet[2], size=1.25, linetype=1) +
      geom_segment(data=datp, aes(x=q7[2], xend=q7[2], y=23, yend=0), colour=colnet[2], size=1.25, linetype=1) + 
      geom_segment(data=datb, aes(x=MEing, xend=MEing, y=30, yend=0), colour=colnet[9], size=1.3, arrow=arrow(length=unit(0.25, "cm"), type="open", angle=30)) +
      geom_text(data=datb, aes(x=MEing, y=-15, label=round(MEing,1)), size=4.25, family="Lato", fontface="bold", colour=colnet[9]) +
      geom_segment(data=datb, aes(x=q8[1], xend=q8[1], y=23, yend=0), colour=colnet[9], size=1.25, linetype=1) +
      geom_segment(data=datb, aes(x=q8[2], xend=q8[2], y=23, yend=0), colour=colnet[9], size=1.25, linetype=1) + 
      theme_new + 
      coord_cartesian(ylim=c(-2.75, 400))

# Add all plots into a single plot

ggg <- list(g1, g2, g3, g4, legend1)
row1 <- plot_grid(ggg[[1]], ggg[[2]], ncol=2, labels = c("(a)", "(b)"), label_size=15, label_fontfamily="Lato", hjust=-0.1, vjust=2, scale=0.98)
row2 <- plot_grid(ggg[[3]], ggg[[4]], ncol=2, labels = c("(c)", "(d)"), label_size=15, label_fontfamily="Lato", hjust=-0.1, vjust=2, scale=0.98)
row3 <- plot_grid(NULL, ggg[[5]], NULL, ncol=3, rel_widths=c(0.25,0.5,0.25))


plot_grid(row3, row1, row2, ncol=1, rel_heights=c(0.15,1,1))

ggsave("Results/curveball.svg", width=11, height=12, units="in", dpi=300)

#rm(datp,datb,simp,simb)
#rm(q1,q2,q3,q4,q5,q6,q7,q8,q9,q10)
#rm(g1,g2,g3,g4,g5,ggg,row1,row2,row3,row4)

```
