---
title: "Network Comparison"
author: "L.A.S."
date: "July 16, 2018"
output: html_document
bibliography: Biblio.bib
editor_options: 
  chunk_output_type: console
---
## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Comparison of Beagle and Potter Cove networks 

```{r readNets, echo=FALSE,message=FALSE,results='asis'}
#
# Load tables 
#
load("Data/topo.RData")

require(knitr)
require(devtools)
require(igraph)
require(dplyr)
# If package EcoNetwork is not installed install it!
#
#detach(package:EcoNetwork,unload = TRUE)
if(!require(EcoNetwork)) {
  install_github("lsaravia/EcoNetwork")
  require(EcoNetwork)
}

g <- readNetwork(c("Potter_FW.txt","Beagle_FW.txt"),"Data")

# Eliminar loops e interacciones repetidas
g[[1]] <- simplify(g[[1]]) 
g[[2]] <- simplify(g[[2]])

ti <- calc_topological_indices(g)

plotTrophLevel(g[[1]],modules=TRUE,main=names(g)[1])

plotTrophLevel(g[[2]],modules=TRUE,main=names(g)[2])

ti <- cbind(ti, rbind(calcIncoherence(g[[1]]),calcIncoherence(g[[2]])))

kable(ti, caption = "Topological indices by Site")
```

## Calculate an plot proportions Top Basal Omnivory Cannibalism

```{r calcProp, echo=FALSE,message=FALSE}

require(dplyr)
require(tidyr)
require(tibble)

ti <- ti %>% rownames_to_column() %>% rename(Name=rowname)
ti <- ti %>% mutate(pTop= Top/Size,pBasal=Basal/Size,pOmnivory=Omnivory/Size)

prop <- ti %>% gather(pTop:pOmnivory,key="Type",value="Proportion") %>% select(Name,Type,Proportion)

require(ggplot2)
ggplot(prop, aes(x=factor(Type), y=Proportion, fill=Name)) + 
  geom_bar(stat="identity", position=position_dodge(), width=0.6) + 
  theme_minimal() + 
  scale_fill_brewer(palette = "Set1", name="Redes tróficas", labels = c("Canal de Beagle", "Caleta Potter")) + 
  labs(y = "Proporción") + 
  theme(axis.title.y = element_text(face="bold", size=rel(2.5), vjust=rel(3)),
        axis.text.y = element_text(color = "black", size = rel(2)), 
        axis.title.x=element_blank(), 
        axis.text.x = element_text(face="bold", color = "black", size = rel(2.5)), 
        legend.title=element_text(face="bold", size=rel(2.5)), 
        legend.text = element_text(size = rel(2.5)))

```

## Calculate an plot proportions of Habitats and Functional groups

```{r calcPropHabFun, echo=FALSE,message=FALSE,results='asis'}

require(dplyr)
require(ggplot2)
require(knitr)
traits <- read.delim("Data/Traits.txt", stringsAsFactors = FALSE)

propHab <- traits %>% group_by( Name,Habitat) %>% summarize(n= n()) %>% mutate(pHabitat=n/sum(n))

kable(propHab, caption = "Habitat by Site")

ggplot(propHab, aes(x=factor(Habitat), y=pHabitat, fill=Name)) +   geom_bar(stat="identity", position=position_dodge(), width=0.6) +   theme_minimal() + 
  scale_fill_brewer(palette = "Set1", name="Redes tróficas", labels = c("Canal de Beagle", "Caleta Potter")) + 
  labs(y = "Proporción", x="Habitat") + 
  theme(axis.title.y = element_text(face="bold", size=rel(2.5), vjust=rel(3)), 
        axis.text.y = element_text(color = "black", size = rel(2)), 
        axis.title.x=element_text(face="bold", size=rel(2.5), vjust=rel(3)),         axis.text.x = element_text(face="bold", color = "black", size = rel(2.5)), 
        legend.title=element_text(face="bold", size=rel(2.5)), 
        legend.text = element_text(size = rel(2.5)))


propFun <- traits %>% group_by( Name,FunctionalGroup) %>% summarize(n= n()) %>% mutate(pFun=n/sum(n))


kable(propFun, caption = "Functional Group by Site")

ggplot(propFun, aes(x=factor(FunctionalGroup), y=pFun, fill=Name)) +  
  geom_bar(stat="identity", position=position_dodge(), width=0.9) +
  theme_minimal() + 
  scale_fill_brewer(palette = "Set1", name="Redes tróficas", labels = c("Canal de Beagle", "Caleta Potter")) + 
  labs(y = "Proporción", x="Grupos funcionales") + 
  theme(axis.title.y = element_text(face="bold", size=rel(2.5), vjust=rel(3)), 
        axis.text.y = element_text(color = "black", size = rel(2)), 
        axis.title.x = element_text(face="bold", size=rel(2.5), vjust=rel(3)),         axis.text.x = element_text(face="bold", color = "black", size = rel(2.5)),
        legend.title=element_text(face="bold", size=rel(2.5)), 
        legend.text = element_text(size = rel(2.5)))

```

## Calculate modularity and Small-world-ness

```{r calcModul, echo=FALSE,message=FALSE,results='asis'}

require(dplyr)
if(!file.exists("Data/SmallWorldNessModularityZScore1000.rds")) {
  tt <- calcModularitySWnessZScore(g[[1]],ncores = 7) %>% mutate(Name=names(g)[1])
  tt <- rbind(tt, calcModularitySWnessZScore(g[[2]],ncores = 7 ) %>% mutate(Name=names(g)[2]))
  saveRDS(tt,"Data/SmallWorldNessModularityZScore1000.rds")
} else {
  tt <- readRDS("Data/SmallWorldNessModularityZScore1000.rds")
}
smallWorldNess <- tt
kable(smallWorldNess)

```

## Calculate topological roles 

```{r calcTopo, echo=FALSE,message=FALSE,results='asis'}

mod_by_red <- vector(mode="list", length=2)

source("R/network_fun.r")
set.seed(123)
modulos<-cluster_spinglass(g[[1]])

mti <- data_frame(Name="PotterCove_FW",Groups=length(modulos$csize),Modularity=modulos$modularity)
mod_by_red[[1]] <- modulos

modulos<-cluster_spinglass(g[[2]])
mti <- mti %>% add_row(Name="Beagle_FW",Groups=length(modulos$csize),Modularity=modulos$modularity)
mod_by_red[[2]] <- modulos

#
# Calc topological roles 1000 simulations
#
tR1 <- calc_topological_roles(g[[1]],100)
tR  <- tR1 %>% group_by(node) %>% summarize(wtmLowCI=quantile(within_module_degree,0.005,na.rm=TRUE),
                                        wtmHiCI=quantile(within_module_degree,0.995,na.rm=TRUE),
                                        amcLowCI=quantile(among_module_conn,0.005,na.rm=TRUE),
                                        amcHiCI=quantile(among_module_conn,0.995,na.rm=TRUE),
                                        within_module_degree=mean(within_module_degree,na.rm=TRUE),
                                        among_module_conn=mean(among_module_conn,na.rm=TRUE))

topoRoles <- tR %>% mutate(Name="PotterCove_FW") 


# Initialize hub_conn
hub_conn <- data.frame()

# Plot and clasify topological roles
hc <- plot_topological_roles(filter(topoRoles,Name=="PotterCove_FW"),g[[1]],mod_by_red[[1]])
hc <-  hc %>% mutate(Name="PotterCove_FW",modulo=mod_by_red[[1]]$membership[node])
hub_conn <- bind_rows(hub_conn,hc)


plotTopoRolesByTLByMod(g[[1]],"PotterCove_FW",c("Fresh detritus","Aged detritus","Necromass"),mod_by_red[[1]],hub_conn,main="Potter Cove")


#
#  Beagle
#

tR1 <- calc_topological_roles(g[[2]],100)
tR  <- tR1 %>% group_by(node) %>% summarize(wtmLowCI=quantile(within_module_degree,0.005,na.rm=TRUE),
                                        wtmHiCI=quantile(within_module_degree,0.995,na.rm=TRUE),
                                        amcLowCI=quantile(among_module_conn,0.005,na.rm=TRUE),
                                        amcHiCI=quantile(among_module_conn,0.995,na.rm=TRUE),
                                        within_module_degree=mean(within_module_degree,na.rm=TRUE),
                                        among_module_conn=mean(among_module_conn,na.rm=TRUE))
#topoRoles <- topoRoles %>% filter(Name!="Beagle_FW")
topoRoles <- bind_rows(topoRoles, tR %>% mutate(Name="Beagle_FW"))

#hub_conn <- hub_conn %>% filter(Name!="Beagle_FW")
hc <-   plot_topological_roles(filter(topoRoles,Name=="Beagle_FW"),g[[2]],mod_by_red[[2]]) 
hc <-  hc %>% mutate(Name="Beagle_FW",modulo=mod_by_red[[2]]$membership[node])
hub_conn <- bind_rows(hub_conn,hc)

#
# Potter Cove
#
require(ggplot2)
require(igraph)
require(dplyr)
require(knitr)
require(tibble)


png("Gráficos/PC_TopoRoles_TL_MOD.png",width=8,height=8,units="in",res=600)
par(mar=c(2,2,2,0),oma=c(2,2,0,0))
plotTopoRolesByTLByMod(g[[1]],"PotterCove_FW",c("Fresh detritus","Aged detritus","Necromass"),mod_by_red[[1]],hub_conn,vertexSizeFactor=2,main="Potter Cove")
dev.off()

#
# Beagle
#
png("Gráficos/Beagle_TopoRoles_TL_MOD.png",width=8,height=8,units="in",res=600)
par(mar=c(2,2,2,0),oma=c(2,2,0,0))
plotTopoRolesByTLByMod(g[[2]],"Beagle_FW",c("Fresh detritus","Aged detritus","Necromass"),mod_by_red[[2]],hub_conn,vertexSizeFactor=2,main="Beagle Channel")
dev.off()

mod_by_red[[2]]$membership
V(g[[2]])[[]]
#
# Todo junto
#

png("Gráficos/AllTopoRoles_TL_MOD.png",width=8,height=8,units="in",res=600)
par(mfrow=c(1,2), mar=c(0,2,0,0), oma=c(2,2,0,0))
plotTopoRolesByTLByMod(g[[1]],"PotterCove_FW",c("Fresh detritus","Aged detritus","Necromass"),mod_by_red[[1]],hub_conn,vertexSizeFactor=2,main="Potter Cove")

plotTopoRolesByTLByMod(g[[2]],"Beagle_FW",c("Fresh detritus","Aged detritus","Necromass"),mod_by_red[[2]],hub_conn,vertexSizeFactor=2,main="Beagle Channel")

require(RColorBrewer)
colnet <- brewer.pal(4,"RdYlGn")

mtext("Modules", side = 1, outer=TRUE, line=0.1,cex=1.2,font=2)
mtext("Trophic level", side = 2, outer=TRUE, line=0.5,cex=1.2,font=2)

par(fig = c(0, 1, 0, 1), oma = c(2, 2, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
legend("center", legend = c("Hub connectors", "Module Connectors", "Module Hubs", "Module Specialists"), 
        col=colnet,pch=19, cex=1.2,xpd = TRUE, inset = c(0,0))

dev.off()



rm(dt,modulo,colnet,mti,tR,tR1,dt,hc)
save.image()


#load(".RData")

```

## Plot modules vs FG and habitat BEAGLE

```{r, echo=FALSE,message=FALSE,results='asis'}

require(dplyr)
require(ggplot2)
require(knitr)

cB <- read.delim(file = "Data/cB.txt", stringsAsFactors = FALSE)

# Módulos vs habitat

ggplot(cB, aes(x=factor(Modulo), y=(Sp), fill=Habitat)) +
  geom_bar(stat= "identity", position="stack") + 
  theme_minimal() + 
  scale_fill_manual(values = c("red", "orange", "gold"), limits = c("pelagic", "benthopelagic", "benthic"), breaks =c("pelagic", "benthopelagic", "benthic"), name = "Habitat", labels = c("Pelágico", "Bentopelágico", "Bentónico")) +
  labs(y = "Especies", x="Módulos") + 
  theme(axis.title.y = element_text(face="bold", size=rel(2), vjust=rel(3)), 
        axis.text.y = element_text(color = "black", size = rel(1.25)), 
        axis.title.x = element_text(face="bold", size=rel(2), vjust=rel(2.)),
        axis.text.x = element_text(face="bold", color = "black", size = rel(2)),
        legend.title=element_text(face="bold", size=rel(2)), 
        legend.text = element_text(size = rel(2)))+
  scale_y_continuous(breaks=c(0, 2099), labels=c("0", "34")) +
  ggtitle ("Canal de Beagle: Módulos vs Hábitat")


# Módulos vs grupos funcionales

ggplot(cB, aes(x=factor(Modulo), y=(Sp), fill=GF)) +
  geom_bar(stat= "identity", position="stack") + 
  theme_minimal() + 
  scale_fill_manual(values = c("grey", "forestgreen", "gold", "firebrick2", "dodgerblue1"), limits = c("detritus", "basal taxa", "zooplankton", "benthos", "fish"), breaks = c("detritus", "basal taxa", "zooplankton", "benthos", "fish"), name = "Grupo funcional", labels = c("Detrito", "Taxones basales", "Zooplancton", "Bentos", "Peces")) + 
  labs(y = "Especies", x="Módulos") + 
  theme(axis.title.y = element_text(face="bold", size=rel(2), vjust=rel(3)), 
        axis.text.y = element_text(color = "black", size = rel(1.25)), 
        axis.title.x = element_text(face="bold", size=rel(2), vjust=rel(2.)),
        axis.text.x = element_text(face="bold", color = "black", size = rel(2)),
        legend.title=element_text(face="bold", size=rel(2)), 
        legend.text = element_text(size = rel(2))) +
  scale_y_continuous(breaks=c(0, 2099), labels=c("0", "34")) +
    ggtitle ("Canal de Beagle: Módulos vs Grupos funcionales")


```

## Plot modules vs FG and habitat POTTER

```{r, echo=FALSE,message=FALSE,results='asis'}

require(dplyr)
require(ggplot2)
require(knitr)

cP <- read.delim(file = "Data/cP.txt", stringsAsFactors = FALSE)

# Módulos vs habitat

ggplot(cP, aes(x=factor(Modulo), y=(Sp), fill=Habitat)) +
  geom_bar(stat= "identity", position="stack") + 
  theme_minimal() + 
  scale_fill_manual(values = c("red", "orange", "gold"), limits = c("pelagic", "benthopelagic", "benthic"), breaks =c("pelagic", "benthopelagic", "benthic"), name = "Habitat", labels = c("Pelágico", "Bentopelágico", "Bentónico")) +
  labs(y = "Especies", x="Módulos") + 
  theme(axis.title.y = element_text(face="bold", size=rel(2), vjust=rel(3)), 
        axis.text.y = element_text(color = "black", size = rel(1.25)), 
        axis.title.x = element_text(face="bold", size=rel(2), vjust=rel(2.)),
        axis.text.x = element_text(face="bold", color = "black", size = rel(2)),
        legend.title=element_text(face="bold", size=rel(2)), 
        legend.text = element_text(size = rel(2))) +
  scale_y_continuous(breaks=c(0, 3366), labels=c("0", "32")) + 
  ggtitle ("Caleta Potter: Módulos vs Hábitat")

# Módulos vs grupos funcionales 

ggplot(cP, aes(x=factor(Modulo), y=(Sp), fill=GF)) +
  geom_bar(stat= "identity", position="stack") + 
  theme_minimal() + 
  scale_fill_manual(values = c("grey", "forestgreen", "gold", "firebrick2", "dodgerblue1"), limits = c("detritus", "basal taxa", "zooplankton", "benthos", "fish"), breaks = c("detritus", "basal taxa", "zooplankton", "benthos", "fish"), name = "Grupo funcional", labels = c("Detrito", "Taxones basales", "Zooplancton", "Bentos", "Peces")) + 
  labs(y = "Especies", x="Módulos") + 
  theme(axis.title.y = element_text(face="bold", size=rel(2), vjust=rel(3)), 
        axis.text.y = element_text(color = "black", size = rel(1.25)), 
        axis.title.x = element_text(face="bold", size=rel(2), vjust=rel(2.)),
        axis.text.x = element_text(face="bold", color = "black", size = rel(2)),
        legend.title=element_text(face="bold", size=rel(2)), 
        legend.text = element_text(size = rel(2))) +
  scale_y_continuous(breaks=c(0, 3366), labels=c("0", "32")) + 
    ggtitle ("Caleta Potter: Módulos vs Grupos funcionales")

```

